### PR TITLE
Adding support for SuperServer installation

### PR DESCRIPTION
**Pull request by rubenqba**
Hi. In my project needed as an essential requirement to install Firebird SuperServer, so I added support for this configuration.
I hope you approve the changes. Still I do not know where to put documentation, as soon as I find out I will add necessary comments.

### CODE REVIEW

**Comment by fdcastel** [comment]
Nice. I see your point, but what do you think about we create ANOTHER package? (e.g.: firebirdsuperserver?) -- The idea of passing parameters to choco install to install a different beast doesn't seem very right to me.

And all the infrastructure are already in place. This new package could just depend of 'firebirdclient' package like 'firebird' does.

Also, I see now I failed to add firebirdTools.ps1 into my git repo. Fixing it right now.

Please, tell me if this would work for you. I'm woking on a prototype of it right now.

**Comment by rubenqba** [comment]
Yes, this solution also work for me.

**Comment by fdcastel** [comment]
Great! Would commit it in a few hours :)

**Comment by fdcastel** [comment]
Well... It's done but I actually create a bigger problem :) Now we have two packages mutually exclusive. Not good.

Talking with other choco developers, they suggested to go back with your original idea of passing arguments to the installer. So, I will merge your PR :)

Thank you very much for the contribution, Rubén!

**Comment by fdcastel** [comment]
Rubén. Could you please also add your version of firebirdTools.ps1 to your repo? :)

**Comment by rubenqba** [comment]
Sorry for late response. Now I push missing file.

**Comment by fdcastel** [comment]
@rubenqba All packages were rewritten to support multiple versions and the multiple installation modes (SuperServer, Classic, etc) so I am closing this one.

**Pull request closed without merging**
