### PR TITLE
Update x-lite for v4.9.8

### PR DESCRIPTION
**Pull request by flcdrg**
- Add autohotkey script and detailed release notes

### CODE REVIEW

**Comment by fdcastel** [comment]
Ingenious :) -- Thanks for the update. 

I'll test it and update the package ASAP. Meanwhile, please do understand that chocolatey package moderation could take several days to approve it in these days :-/

**Comment by flcdrg** [comment]
No worries.

The queue is pretty short last time I looked. I'm also a moderator so I can review the package if you let me know when you submit it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fdcastel** [comment]
Great to know! I warned you about the delay because my last submission (for Firebird database, also in this repository) took 4 days to approve (and that was 3 weeks ago). 

I'm merging the changes now. I believe I found a small optimization in the AHK script. Please review it when you can.

**Comment by fdcastel** [comment]
I've created a [new branch](https://github.com/fdcastel/chocolatey-packages/tree/fdcastel-v4.9.8) with your changes, rebased at HEAD and with minor changes -- Please review and let me know what you think 😉

**Comment by flcdrg** [comment]
Yeah, that looks fine to me.
👍

**Comment by fdcastel** [comment]
All done and pushed to chocolatey site.

Thanks again for the PR, David! Much appreciated! 😄 👍

**Comment by fdcastel** [comment]
Hm. It appears the new package is hanging in automated chocolatey tests. 

As a moderator, could you bring us some light into this problem? 😄 

P.S.: I had to add the `notsilent` tag, as instructed by the automated checks.

**Comment by flcdrg** [comment]
Hmm.. just went back had another look. I notice now that as well as adding comments, you did alter the AHK tab and space sequence. Are you sure that didn't break anything?

I know the original sequence I submitted was a bit odd and didn't correspond with what I typed manually, but it did seem to work so I didn't dig too deep to figure out why the difference.

Looking at the [Gist](https://gist.github.com/choco-bot/5808310cba32d22b8535a80e6040cf01#file-install-txt-L1388) from the install log, the last thing it does is try and run the installer, which makes me think it is hanging waiting for the license screen to be completed.

**Comment by fdcastel** [comment]
I'm pretty sure the version submitted doesn't hang. I tested it in Windows 10 and in Windows Server 2016 and in both cases the AHK script worked flawlessly.

You can try it yourself: get the latest HEAD, build it with `choco pack` and install it with `choco install x-lite.4.9.8.84253.nupkg`. 

If memory serves me, the chocolatey automated test environment runs in Windows Server 2012. I will try to test with one of those as soon as I can.

**Comment by flcdrg** [comment]
Hmm.. i'll see if I can test it on 2012. That dialog is a weird thing - it must be just a rendered window as there's no windows controls that the AHK script can identify (hence just the blind tabbing and spacing to drive it).

**Comment by fdcastel** [comment]
Hm. Bingo!

When running in Windows 8.1 I got this:

image

and the installer finished with the message:

`A reboot is required following .NET installation - reboot then run installer again.`

So. I restarted the computer and tried again. Then it worked!

I really don't know what to do now. It appears to be a problem with chocolatey tests?

Or maybe we should put a requires clause for [this package](https://chocolatey.org/packages/dotnet4.6.2)? I often don't like packages with a red light but... Hey! Look who approved it? 😄

**Comment by flcdrg** [comment]
Ha.. I just got the same results on a 2012 Server VM I spun up!

We need to add a dependency on dotnet4.6.2 and request an exemption from testing from a 'super admin' (Rob or Gary) as the VM will want to reboot.

**Comment by fdcastel** [comment]
Merged and pushed to chocolatey 😉  -- Let's wait, now. Thanks, again, David!

**Comment by flcdrg** [comment]
Next steps:

- [ ] add a comment to https://chocolatey.org/packages/x-lite/4.9.8.84253 indicating you need a testing exception because of the dotnet dependency
- [ ] Post to https://gitter.im/chocolatey/chocolatey.org asking for a moderator to grant your testing exemption request

The second is because they won't necessarily notice the first, but the first is required to help with leaving an auditing trail.

**Comment by fdcastel** [comment]
Nice! Done! ;)

**Pull request closed without merging**
